[package]
name = "stm32wl55-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.3"
panic-halt = "0.2.0"
stm32wlxx-hal = { version="0.6.1", features = ["stm32wl5x_cm4"] }

[[bin]]
name = "baremetal_blinky"
test = false
bench = false